# Workflow name
name: 'Lint'

# Event for the workflow
on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# List of jobs
jobs:
  lint-test:
    name: Lint & Test
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        # ðŸ‘‡ Install dependencies
        run: yarn
        # ðŸ‘‡ Lint and test code
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn storybook:test:ci

